#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    methods: POST

register:
    path: /register
    methods: POST
    controller: App\Controller\RegistrationController::index